import { Download,Info } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/common/PageHeader'
import { ResourceState } from '../components/common/ResourceState'
import { SectionCard,SummaryCard } from '../components/common/Cards'
import { StatusBadge } from '../components/common/StatusBadge'
import { TelemetryChart } from '../components/telemetry/TelemetryChart'
import { useServiceData } from '../hooks/useServiceData'
import { telemetryService } from '../services'
import { downloadCsv } from '../utils/csv'
import { formatDateTime } from '../utils/formatters'

export function HistoryPage() {
  const resource=useServiceData(telemetryService.getTelemetryHistory)
  const [selectedId,setSelectedId]=useState<string|null>(null)
  const records=resource.data??[]
  const selected=records.find((record)=>record.id===selectedId)??records[0]
  const stats=records.length?({before:(records.reduce((sum,row)=>sum+row.before.turbidity,0)/records.length).toFixed(2),after:(records.reduce((sum,row)=>sum+row.after.turbidity,0)/records.length).toFixed(2)}):({before:'—',after:'—'})
  const exportRows=()=>downloadCsv('telemetry.csv',records.map((row)=>({timestamp:row.timestamp,test_run_id:row.testRunId,before_ph:row.before.pH,after_ph:row.after.pH,before_turbidity_ntu:row.before.turbidity,after_turbidity_ntu:row.after.turbidity,before_tds_ppm:row.before.TDS,after_tds_ppm:row.after.TDS})))
  if(resource.status!=='success'||!selected)return <div className="page-grid"><PageHeader title="Telemetry History" description="Review representative pre- and post-filtration sensor records; live telemetry is not connected" badge="Representative data"/><ResourceState status={resource.status} error={resource.error} loadingLabel="Loading telemetry history…" emptyLabel="No telemetry records available."/></div>
  return <div className="page-grid"><PageHeader title="Telemetry History" description="Review representative pre- and post-filtration sensor records; live telemetry is not connected" badge="Representative data" actions={<button type="button" className="button-primary" onClick={exportRows}><Download size={16}/>Export CSV</button>}/>
  <div className="summary-grid"><SummaryCard label="Before filtration average" value={`${stats.before} NTU`} detail="Mean across selected records"/><SummaryCard label="After filtration average" value={`${stats.after} NTU`} detail="Descriptive comparison only" tone="good"/><SummaryCard label="Before minimum / maximum" value="9.26 – 9.43" detail="Recorded range, NTU"/><SummaryCard label="After minimum / maximum" value="0.69 – 0.82" detail="Recorded range, NTU" tone="good"/></div>
  <div className="notice"><Info size={17}/><span>Laboratory validation is tracked separately from sensor telemetry.</span></div>
  <SectionCard title="Representative Sensor Trends" description="Before vs After sample series" action={<span className="eyebrow text-hydro">Turbidity</span>}><TelemetryChart/></SectionCard>
  <div className="detail-grid"><SectionCard title="Representative telemetry records" description={`${records.length} sample records`}><div className="table-wrap"><table className="data-table"><thead><tr><th>Timestamp</th><th>Test Run</th><th>Pre / Post pH</th><th>Pre / Post Turbidity</th><th>Pre / Post TDS</th><th>Action</th></tr></thead><tbody>{records.map((record)=><tr key={record.id} data-selected={selected.id===record.id}><td className="mono">{record.timestamp.slice(11,19)}</td><td className="mono">{record.testRunId}</td><td className="mono">{record.before.pH.toFixed(2)} / <span className="text-hydro">{record.after.pH.toFixed(2)}</span></td><td className="mono">{record.before.turbidity.toFixed(2)} / <span className="text-hydro">{record.after.turbidity.toFixed(2)}</span></td><td className="mono">{record.before.TDS} / <span className="text-hydro">{record.after.TDS}</span></td><td><button className="button-quiet" type="button" onClick={()=>setSelectedId(record.id)}>Inspect</button></td></tr>)}</tbody></table></div></SectionCard><SectionCard title="Sample Record Inspector" action={<span className="eyebrow rounded bg-blue-100 px-2 py-1 text-hydro">{selected.timestamp.slice(11,19)} UTC</span>}><div className="space-y-3"><div className="subpanel p-3"><div className="eyebrow text-muted">Sample Test Run / Device</div><div className="mono mt-1 text-xs">{selected.testRunId} · {selected.deviceId}</div><div className="mt-2"><StatusBadge>Sample record</StatusBadge></div></div>{(['before','after'] as const).map((sensorStage)=><div className="subpanel p-3" key={sensorStage}><h4 className="text-sm font-semibold text-hydro">{sensorStage==='before'?'Before Filtration':'After Filtration'}</h4><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><span className="text-muted">pH</span><div className="mono text-base">{selected[sensorStage].pH.toFixed(2)}</div></div><div><span className="text-muted">Turbidity</span><div className="mono text-base">{selected[sensorStage].turbidity.toFixed(2)} NTU</div></div><div><span className="text-muted">TDS</span><div className="mono text-base">{selected[sensorStage].TDS} ppm</div></div><div><span className="text-muted">Flow</span><div className="mono text-base">{selected[sensorStage].flowRate.toFixed(1)} L/min</div></div></div></div>)}<div className="text-xs text-muted">Recorded {formatDateTime(selected.timestamp)}</div><div className="notice">Laboratory association: Validation Pending</div></div></SectionCard></div></div>
}
