import { Download,Plus } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/common/PageHeader'
import { SectionCard,SummaryCard } from '../components/common/Cards'
import { Modal } from '../components/common/Overlay'
import { ResourceState } from '../components/common/ResourceState'
import { StatusBadge } from '../components/common/StatusBadge'
import { useActionFeedback } from '../hooks/useActionFeedback'
import { useServiceData } from '../hooks/useServiceData'
import { maintenanceService } from '../services'
import { downloadCsv } from '../utils/csv'
import { formatDateTime } from '../utils/formatters'

export function MaintenancePage() {
  const {actionError,pending,runAction}=useActionFeedback()
  const recordsResource=useServiceData(maintenanceService.getMaintenanceRecords); const remindersResource=useServiceData(maintenanceService.getMaintenanceReminders)
  const [selectedId,setSelectedId]=useState<string|null>(null); const [open,setOpen]=useState(false); const [newComponent,setNewComponent]=useState('ESP32 Controller'); const [newNotes,setNewNotes]=useState('')
  const records=recordsResource.data??[]; const reminders=remindersResource.data??[]; const selected=records.find((record)=>record.id===selectedId)??records[0]
  const exportRows=()=>downloadCsv('maintenance.csv',records.map((r)=>({maintenance_id:r.id,date:r.date,component:r.component,type:r.type,description:r.description,status:r.status,performed_by:r.performedBy,notes:r.notes})))
  const addRecord=async()=>{const record=await maintenanceService.createMaintenanceRecord({component:newComponent,notes:newNotes});recordsResource.setData((items)=>items?[record,...items]:[record]);setSelectedId(record.id);setNewNotes('');setOpen(false)}
  const unavailable=[recordsResource,remindersResource].find((resource)=>resource.status==='loading'||resource.status==='error')
  if(unavailable)return <div className="page-grid">{actionError&&<div className="notice text-danger" role="alert">{actionError}</div>}{pending&&<div className="notice" role="status">Saving to the API…</div>}<PageHeader title="Maintenance" description="Review API-backed maintenance records; recorded data does not prove physical servicing" badge="API records"/><ResourceState status={unavailable.status} error={unavailable.error} loadingLabel="Loading maintenance records…"/></div>
  if(!selected)return <div className="page-grid">{actionError&&<div className="notice text-danger" role="alert">{actionError}</div>}{pending&&<div className="notice" role="status">Saving to the API…</div>}<PageHeader title="Maintenance" description="No API maintenance records are available yet." badge="API records"/><SectionCard title="Create the first maintenance record"><div className="field"><label htmlFor="first-maintenance-component">Component</label><select id="first-maintenance-component" className="control" value={newComponent} onChange={(event)=>setNewComponent(event.target.value)}><option>ESP32 Controller</option><option>Ultrafiltration Unit</option><option>UV-C Unit</option><option>Booster Pump</option><option>Sensor Suite</option></select></div><div className="field mt-3"><label htmlFor="first-maintenance-notes">Inspection notes</label><textarea id="first-maintenance-notes" className="control min-h-24" value={newNotes} onChange={(event)=>setNewNotes(event.target.value)}/></div><p className="mt-3 text-xs text-muted">This saves through the API. Record only an inspection actually performed; no hardware command is issued.</p><button className="button-primary mt-3" type="button" onClick={()=>void runAction(addRecord)}>Save record</button></SectionCard></div>
  return <div className="page-grid">{actionError&&<div className="notice text-danger" role="alert">{actionError}</div>}{pending&&<div className="notice" role="status">Saving to the API…</div>}<PageHeader title="Maintenance" description="Review API-backed maintenance records; recorded data does not prove physical servicing" badge="API records" actions={<><button className="button-secondary" type="button" onClick={exportRows}><Download size={16}/>Export Maintenance CSV</button><button className="button-primary" type="button" onClick={()=>setOpen(true)}><Plus size={16}/>New Maintenance Record</button></>}/><div className="summary-grid"><SummaryCard label="Maintenance records" value={records.length} detail="Documented API entries"/><SummaryCard label="Pending review" value={records.filter((r)=>r.status==='Review Needed').length} detail="Follow-up inspection items" tone="danger"/><SummaryCard label="Completed" value={records.filter((r)=>r.status==='Completed').length} detail="Documented activities" tone="good"/><SummaryCard label="Maintenance reminders" value={reminders.length} detail="Recorded reminders" tone="warn"/></div>
  <SectionCard title="System Maintenance Status" description="Latest loaded documentation by component"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[...new Set(records.map((record)=>record.component))].map((component)=><div className="subpanel p-3" key={component}><strong className="text-sm">{component}</strong><p className="mt-2 text-xs text-muted">Latest record: {records.find((record)=>record.component===component)?.status??"Not recorded"}</p></div>)}</div></SectionCard>
  <div className="grid gap-4 xl:grid-cols-2"><SectionCard title="UV-C Operating Hours" action={<StatusBadge>Pending</StatusBadge>}><div className="subpanel p-4"><div className="eyebrow text-muted">Manual runtime log</div><div className="mono mt-2 text-2xl font-semibold text-hydro">Not available</div></div><p className="mt-3 text-xs text-muted">No verified UV-C runtime telemetry is available.</p></SectionCard><SectionCard title="Filter Maintenance Reminder Status" action={<StatusBadge>Pending</StatusBadge>}><div className="subpanel p-4"><div className="eyebrow text-muted">Reminder state</div><div className="mt-2 font-semibold">Reminder Configuration Pending</div></div><p className="mt-3 text-xs text-muted">No pressure-based filter-health measurement or remaining-life calculation is available.</p></SectionCard></div>
  <div className="detail-grid"><div className="page-grid"><SectionCard title="Maintenance Records" description={`${records.length} loaded records`}><div className="table-wrap"><table className="data-table"><thead><tr><th>Maintenance ID</th><th>Date</th><th>Component</th><th>Type</th><th>Description</th><th>Status</th><th>Action</th></tr></thead><tbody>{records.map((record)=><tr key={record.id} data-selected={selected.id===record.id}><td className="mono font-semibold text-hydro">{record.id}</td><td className="mono">{record.date.slice(0,16).replace('T',' ')}</td><td>{record.component}</td><td>{record.type}</td><td>{record.description}</td><td><StatusBadge>{record.status}</StatusBadge></td><td><button className="button-quiet" type="button" onClick={()=>setSelectedId(record.id)}>Inspect</button></td></tr>)}</tbody></table></div></SectionCard><SectionCard title="Maintenance Reminders" description="API-backed reminders; scheduling rules remain unapproved"><div className="space-y-2">{reminders.map((reminder)=><div className="subpanel flex flex-wrap items-center justify-between gap-2 p-3" key={reminder.id}><div><span className="mono text-xs font-semibold text-hydro">{reminder.id}</span><span className="ml-2 text-sm font-semibold">{reminder.component}: {reminder.label}</span></div><div className="flex items-center gap-2"><span className="mono text-xs">Due {reminder.dueDate??'not set'}</span><StatusBadge>{reminder.status}</StatusBadge></div></div>)}</div></SectionCard><SectionCard title="Recent Maintenance Activity">{records.slice(0,3).map((record)=><div className="grid gap-1 border-b border-slate-200 py-2 text-xs sm:grid-cols-[150px_1fr_auto]" key={record.id}><span className="mono">{record.date.slice(0,16).replace('T',' ')}</span><strong className="text-hydro">{record.component}</strong><span>{record.performedBy}</span></div>)}</SectionCard></div><SectionCard title="Maintenance Inspector" action={<StatusBadge>{selected.status}</StatusBadge>}><div className="space-y-3"><div><div className="eyebrow text-muted">Maintenance ID</div><div className="mono mt-1 text-lg font-semibold text-hydro">{selected.id}</div></div><div className="subpanel grid gap-3 p-3 text-xs"><div><span className="text-muted">Recorded</span><div className="mono">{formatDateTime(selected.date)}</div></div><div><span className="text-muted">Component / type</span><div>{selected.component} · {selected.type}</div></div><div><span className="text-muted">Record attribution</span><div>{selected.performedBy}</div></div></div><div><div className="eyebrow text-muted">Inspection description</div><p className="mt-1 text-sm leading-relaxed">{selected.description}</p></div><div><div className="eyebrow text-muted">Parts / materials notes</div><p className="mt-1 text-sm">{selected.notes}</p></div></div></SectionCard></div>
  <Modal open={open} title="New Maintenance Record" onClose={()=>setOpen(false)} footer={<><button className="button-secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="button-primary" type="button" onClick={()=>void runAction(addRecord)}>Save record</button></>}><div className="space-y-3"><div className="field"><label htmlFor="component">Component</label><select id="component" name="maintenance-component" autoComplete="off" className="control" value={newComponent} onChange={(event)=>setNewComponent(event.target.value)}><option>ESP32 Controller</option><option>Ultrafiltration Unit</option><option>UV-C Unit</option><option>Booster Pump</option><option>Sensor Suite</option></select></div><div className="field"><label htmlFor="inspection-notes">Inspection notes</label><textarea id="inspection-notes" name="inspection-notes" autoComplete="off" className="control min-h-24" placeholder="Enter inspection notes…" value={newNotes} onChange={(event)=>setNewNotes(event.target.value)}/></div><div className="notice">This record is saved through the API. It does not issue hardware commands.</div></div></Modal></div>
}
