import { Check,LockKeyhole,RotateCcw,ShieldCheck } from 'lucide-react'
import { useEffect,useState } from 'react'
import { PageHeader } from '../components/common/PageHeader'
import { ResourceState } from '../components/common/ResourceState'
import { SectionCard } from '../components/common/Cards'
import { StatusBadge } from '../components/common/StatusBadge'
import { useServiceData } from '../hooks/useServiceData'
import { useAuth } from '../hooks/useAuth'
import { deviceService,settingsService,usersService } from '../services'

const sections=[['general','General'],['monitoring','Monitoring & Data'],['thresholds','Alert Thresholds'],['device','Device & Connectivity'],['notifications','Notifications'],['users','Users & Access'],['export','Research & Export']] as const
const pendingSettings=[['Sensor Sampling Interval','Configuration Pending'],['Database Recording Interval','Configuration Pending'],['Target Volume','Configuration Pending'],['Maximum Cycle Duration','Configuration Pending'],['Data Stale Detection','Configuration Pending'],['Device Offline Detection','Configuration Pending']] as const
const thresholds=[['pH Level','pH'],['Turbidity','NTU'],['Total Dissolved Solids (TDS)','ppm'],['Water Temperature','°C'],['Flow Rate','L/min']] as const
export function SettingsPage() {
  const auth=useAuth()
  const settingsResource=useServiceData(settingsService.getSettings); const usersResource=useServiceData(usersService.getUsers); const deviceResource=useServiceData(deviceService.getDeviceStatus)
  const [saved,setSaved]=useState(false)
  const settings=settingsResource.data; const users=usersResource.data??[]; const device=deviceResource.data
  const toggle=(key:keyof NonNullable<typeof settings>['notifications'])=>{setSaved(false);settingsResource.setData((value)=>value?{...value,notifications:{...value.notifications,[key]:!value.notifications[key]}}:value)}
  const reset=async()=>{settingsResource.setData(await settingsService.getSettings());setSaved(false)}
  const save=async()=>{if(!settings)return;settingsResource.setData(await settingsService.updateSettings(settings));setSaved(true)}
  useEffect(()=>{const targetId=window.location.hash.slice(1);if(!targetId)return;const timer=window.setTimeout(()=>document.getElementById(targetId)?.scrollIntoView(),100);return()=>window.clearTimeout(timer)},[])
  const unavailable=[settingsResource,usersResource,deviceResource].find((resource)=>resource.status!=='success')
  if(unavailable||!settings||!device)return <div className="page-grid"><PageHeader title="Settings" description="Configure application, monitoring, alert, notification, and access preferences" badge="System configuration"/><ResourceState status={unavailable?.status??'loading'} error={unavailable?.error} loadingLabel="Loading settings…"/></div>
  const notifications=settings.notifications
  return <div className="page-grid"><PageHeader title="Settings" description="Configure application, monitoring, alert, notification, and access preferences" badge="System configuration" actions={<><button type="button" className="button-secondary" onClick={()=>void reset()}><RotateCcw size={15}/>Cancel / Reset Changes</button><button type="button" className="button-primary" onClick={()=>void save()}><Check size={15}/>Save Changes</button></>}/>{saved&&<div className="notice border-l-emerald-600 bg-emerald-50" role="status">Settings saved.</div>}
  <div className="grid items-start gap-4 xl:grid-cols-[250px_minmax(0,1fr)]"><aside className="panel sticky top-20 p-2"><div className="flex items-center justify-between px-2 py-3"><span className="eyebrow text-muted">Settings modules</span><span className="mono text-[10px]">7 sections</span></div><nav className="space-y-1" aria-label="Settings sections">{sections.map(([id,label])=><a className="flex items-center rounded-md px-3 py-2 text-sm text-slate-700 hover:bg-panel-soft hover:text-hydro" href={`#${id}`} key={id}>{label}</a>)}</nav><div className="notice mt-3"><ShieldCheck size={16}/><span>Sensitive credentials, database secrets, device tokens, Wi-Fi passwords, and notification-service credentials are managed outside this interface.</span></div></aside><div className="page-grid">
  <SectionCard id="general" title="General Settings" action={<span className="eyebrow text-muted">System identity</span>} className="scroll-mt-20"><div className="grid gap-3 md:grid-cols-2"><div className="field"><label htmlFor="system-name">System name</label><input id="system-name" name="system-name" className="control" value={settings.systemName} readOnly/></div><div className="field"><label htmlFor="device-name">Device display name</label><input id="device-name" name="device-display-name" autoComplete="off" spellCheck={false} className="control mono" value={settings.deviceDisplayName} onChange={(event)=>{setSaved(false);settingsResource.setData((value)=>value?{...value,deviceDisplayName:event.target.value}:value)}}/></div><div className="field"><span className="eyebrow text-muted">Timezone</span><div className="control mono">{settings.timezone}</div></div><div className="grid grid-cols-2 gap-3"><div className="field"><span className="eyebrow text-muted">Date format</span><div className="control mono">{settings.dateFormat}</div></div><div className="field"><span className="eyebrow text-muted">Time format</span><div className="control mono">{settings.timeFormat}</div></div></div><div className="subpanel flex items-center justify-between gap-3 p-3 md:col-span-2"><div><div className="text-sm font-semibold">{auth.status==='authenticated'?auth.user.name:'User'}</div><div className="mono text-[10px] text-muted">Current authenticated session</div></div><StatusBadge>Active</StatusBadge></div></div></SectionCard>
  <SectionCard id="monitoring" title="Monitoring & Data Configuration" action={<StatusBadge>Pending</StatusBadge>} className="scroll-mt-20"><div className="grid gap-3 md:grid-cols-2">{pendingSettings.map(([label,value])=><div className="subpanel p-3" key={label}><div className="flex items-start justify-between gap-2"><span className="eyebrow text-muted">{label}</span><StatusBadge>Pending</StatusBadge></div><div className="mono mt-3 text-lg font-semibold">{value}</div>{label==='Database Recording Interval'&&<p className="mt-2 text-xs text-muted">Client-suggested initial recording/transmission target: approximately 30 seconds. Final value remains subject to integration testing.</p>}</div>)}</div><div className="notice mt-3">When live telemetry is unavailable, the interface must retain the latest reading while clearly marking it stale or offline. Final stale/offline rules remain pending.</div></SectionCard>
  <SectionCard id="thresholds" title="Water-Quality Alert Thresholds" action={<StatusBadge>Pending</StatusBadge>} className="scroll-mt-20"><div className="notice mb-3">Threshold values must be approved by the research team before use. No arbitrary values are shown.</div><div className="table-wrap"><table className="data-table"><thead><tr><th>Parameter</th><th>Unit</th><th>Lower Limit</th><th>Upper Limit</th><th>Approval State</th></tr></thead><tbody>{thresholds.map(([parameter,unit])=><tr key={parameter}><td>{parameter}</td><td className="mono">{unit}</td><td className="mono">—</td><td className="mono">—</td><td><StatusBadge>Pending</StatusBadge> <span className="ml-1 text-xs">Research-Team Approval</span></td></tr>)}</tbody></table></div></SectionCard>
  <SectionCard id="device" title="Device & Connectivity" action={<StatusBadge>{device.connection}</StatusBadge>} className="scroll-mt-20"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Device identifier',device.deviceId],['Microcontroller',device.controller],['Link state',device.connection],['Wi-Fi telemetry link',device.wifiConnection]].map(([label,value])=><div className="subpanel p-3" key={label}><div className="eyebrow text-muted">{label}</div><div className="mono mt-2 text-xs font-semibold">{value}</div></div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{[['Pump Control','Pending Confirmation'],['UV-C Control','Pending Confirmation'],['Relay Integration','Pending Hardware Integration'],['Hardware Fail-Safe','Pending Hardware Integration']].map(([label,value])=><div className="subpanel flex items-center justify-between gap-3 p-3 text-sm" key={label}><span>{label}</span><StatusBadge>Pending</StatusBadge><span className="sr-only">{value}</span></div>)}</div></SectionCard>
  <SectionCard id="notifications" title="Notification Preferences" action={<span className="eyebrow text-muted">Application event subscriptions</span>} className="scroll-mt-20"><div className="grid gap-2 md:grid-cols-2">{([['offline','Device Offline Alarm'],['sensor','Sensor Error & Faults'],['noFlow','No Flow Condition'],['waterQuality','Water-Quality Warning'],['pump','Pump Status Warning'],['uvc','UV-C Status Warning'],['maintenance','Maintenance Reminder']] as const).map(([key,label])=><div className="subpanel flex items-center justify-between gap-3 p-3" key={key}><div><div className="text-sm font-semibold">{label}</div><div className="text-xs text-muted">Application notification preference</div></div><button type="button" role="switch" aria-checked={notifications[key]} aria-label={`Toggle ${label}`} onClick={()=>toggle(key)} className={`relative h-6 w-11 rounded-full border transition-colors ${notifications[key]?'border-hydro bg-hydro':'border-slate-300 bg-slate-200'}`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-transform ${notifications[key]?'left-[21px]':'left-0.5'}`}/></button></div>)}</div><div className="subpanel mt-3 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="eyebrow text-muted">SMS Provider</div><div className="mt-1 font-semibold">Not Configured</div></div><StatusBadge>Pending</StatusBadge></div><div className="mt-2 flex items-center gap-2 text-xs text-muted"><LockKeyhole size={14}/>API keys, tokens, and credentials are never entered or displayed here.</div></div></SectionCard>
  <SectionCard id="users" title="Users & Access Management" action={<span className="eyebrow text-muted">Software-level roles only</span>} className="scroll-mt-20"><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Email / Username</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td className="font-semibold">{user.name}</td><td className="mono">{user.email}</td><td><StatusBadge tone={user.role==='Administrator'?'Active':user.role==='Researcher'?'Information':'Pending'}>{user.role}</StatusBadge></td><td><StatusBadge>{user.status}</StatusBadge></td><td><button type="button" className="button-quiet">Edit Role</button></td></tr>)}</tbody></table></div><div className="notice mt-3">Role definitions remain subject to authorization approval. These software roles do not grant hardware actuator permissions.</div></SectionCard>
  <SectionCard id="export" title="Research & Export Preferences" action={<span className="eyebrow text-muted">Dataset standardization</span>} className="scroll-mt-20"><div className="grid gap-3 md:grid-cols-2"><div className="subpanel p-3"><div className="eyebrow text-muted">CSV telemetry export defaults</div><div className="mt-3 flex items-center justify-between"><span className="text-sm">Default date range</span><span className="mono text-sm font-semibold text-hydro">Last 7 Days</span></div>{['Include Test Run ID','Include Before/After Telemetry','Include Alert Association','Include Calibration Association','Include Laboratory Validation Association'].map((item)=><div className="mt-2 flex items-center justify-between border-t border-slate-200 pt-2 text-xs" key={item}><span>{item}</span><span className="mono text-good">YES</span></div>)}</div><div className="space-y-3"><div className="subpanel p-3"><div className="eyebrow text-muted">Data retention policy</div><div className="mt-2 font-semibold">Not Configured</div><p className="mt-2 text-xs text-muted">No automatic deletion or retention period has been configured.</p></div><div className="subpanel p-3"><div className="eyebrow text-muted">Maintenance reminder configuration</div><div className="mt-2 font-semibold">No automated schedules currently active</div></div></div></div></SectionCard>
  <div className="notice"><ShieldCheck size={17}/><span>Configuration related to water-quality thresholds, filtration-cycle logic, hardware controls, and safety behavior must be confirmed by the research and hardware teams before deployment.</span></div></div></div></div>
}
